# -*- coding: utf-8 -*-
"""Copy of FINAL_PROJECT_(MHS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipTJkVxTm7i-y7uzSMO6pqMw7oNWqASX

1.   Age
2.   Gender
3.   Sleep Duration= Slpdrn
4.   Exercise frequency= Exerq
5.   Social Support Level= Ssl
6.   Work Stress Level= Wsl
7.   Alcohol Consumption= Alcsm
8.   Smoking Habit= Smkhbt
9.   Financial Stress= Fist
10.  Diet Quaility= Diqlt
11.  Family History of Mental illness= Fhomi
12.  Relationship Satisfaction= Rlst
13.  Substance use History= Suh
14.  Self-Esteem Score= Ses
15.  Social Media usage= Smu
16.  Anxiety Level= Alvl
17.  Depression Level= Dplvl
18.  work-life balance= Wlb
19.  Traumatic Experience history= Teh
20.  Mental Health Score= Mhs

# Feature selection
"""

# Data Preprocessing

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

# Set the style for our plots
plt.style.use('default')

# Load the dataset
df = pd.read_csv('/content/Mental_Health_final.csv')

# Check the shape of the dataset
print("Dataset shape:", df.shape)

# Check for missing values
missing_values = df.isnull().sum()
print("Missing values in each column:")
print(missing_values)

# Handling Missing Values: Drop rows with excessive missing data
df = df.dropna()
print("Rows after dropping missing values:", df.shape)

# Display the first few rows of the preprocessed data
print("First 5 rows of the preprocessed data:")
print(df.head())

# Summary statistics of the preprocessed data
print("Summary statistics of the preprocessed data:")
print(df.describe())

# Check for outliers in numerical columns using box plots
plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols):
    if col != 'Mhs':  # Exclude the dependent variable for now
        plt.subplot(3, 5, i+1)
        sns.boxplot(y=df[col])
        plt.title(col)
plt.tight_layout()
plt.show()

# Save the preprocessed data
df.to_csv('preprocessed_mental_health.csv', index=False)
print("Preprocessed data saved to 'preprocessed_mental_health.csv'")

# Box plots for categorical variables vs Mental Health Score
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
fig, axes = plt.subplots(1, len(categorical_cols), figsize=(15, 7))

for i, col in enumerate(categorical_cols):
    sns.boxplot(x=df[col], y=df['Mhs'], ax=axes[i], palette=['#766CDB', '#DA847C', '#7CD9A5'])
    axes[i].set_title(f'{col} vs Mhs', fontsize=16, fontweight='semibold', color='#222222', pad=15)
    axes[i].set_xlabel(col, fontsize=14, color='#333333', labelpad=10)
    axes[i].set_ylabel('Mental Health Score', fontsize=14, color='#333333', labelpad=10)
    axes[i].tick_params(labelsize=12, colors='#555555')
    axes[i].set_axisbelow(True)
    for spine in axes[i].spines.values():
        spine.set_color('#333333')

plt.tight_layout()
plt.show()

# Exploratory Data Analysis (EDA)

import seaborn as sns
from scipy import stats

# Set the style for our plots
plt.style.use('default')

# Distribution of the dependent variable (Mental Health Score)
plt.figure(figsize=(9, 6))
ax = sns.histplot(df['Mhs'], kde=True, color='#766CDB')
ax.set_title('Distribution of Mental Health Score', fontsize=20, fontweight='semibold', color='#222222', pad=15)
ax.set_xlabel('Mental Health Score', fontsize=16, color='#333333', labelpad=10)
ax.set_ylabel('Frequency', fontsize=16, color='#333333', labelpad=10)
ax.tick_params(labelsize=14, colors='#555555')
ax.set_axisbelow(True)
ax.grid(True, linestyle='--', alpha=0.7, color='#E0E0E0')
for spine in ax.spines.values():
    spine.set_color('#333333')
plt.tight_layout()
plt.show()

# Correlation heatmap
plt.figure(figsize=(12, 10))
numerical_df = df.select_dtypes(include=['int64', 'float64'])
correlation_matrix = numerical_df.corr()
mask = np.triu(np.ones_like(correlation_matrix, dtype=bool))
ax = sns.heatmap(correlation_matrix, mask=mask, annot=True, fmt=".2f", cmap='coolwarm',
                 linewidths=0.5, annot_kws={"size": 10})
ax.set_title('Correlation Heatmap of Numerical Variables', fontsize=20, fontweight='semibold', color='#222222', pad=15)
plt.tight_layout()
plt.show()

# Correlation with Mental Health Score
correlations_with_mhs = correlation_matrix['Mhs'].sort_values(ascending=False)
print("Correlations with Mental Health Score:")
print(correlations_with_mhs)

plt.figure(figsize=(12, 6))
df.hist(bins=30, figsize=(15, 12))
plt.show()

# Pairplot for key variables
key_vars = ['Mhs', 'Slpdrn', 'Exerq', 'Ssl', 'Wlb', 'Ses']
plt.figure(figsize=(12, 10))
sns.pairplot(df[key_vars], diag_kind='kde', plot_kws={'alpha': 0.6, 'edgecolor': 'k', 's': 40},
             diag_kws={'color': '#766CDB'})
plt.suptitle('Pairplot of Key Variables', fontsize=20, fontweight='semibold', color='#222222', y=1.02)
plt.tight_layout()
plt.show()

# Checking for normality of the dependent variable

plt.figure(figsize=(9, 6))
stats.probplot(df['Mhs'], dist="norm", plot=plt)
plt.title('Q-Q Plot for Mental Health Score', fontsize=20, fontweight='semibold', color='#222222', pad=15)
plt.xlabel('Theoretical Quantiles', fontsize=16, color='#333333', labelpad=10)
plt.ylabel('Ordered Values', fontsize=16, color='#333333', labelpad=10)
plt.grid(True, linestyle='--', alpha=0.7, color='#E0E0E0')
plt.tight_layout()
plt.show()

print("Skewness of Mental Health Score:", stats.skew(df['Mhs']))
print("Kurtosis of Mental Health Score:", stats.kurtosis(df['Mhs']))

"""# Replacing values of Qualitative variable"""

df["Gender"].replace({"Male": 1, "Female": 2, "Other":0}, inplace=True)
df["Smkhbt"].replace({"Yes": 1, "No": 2}, inplace=True)
df["Fhomi"].replace({"Yes": 1, "No": 2}, inplace=True)
df["Suh"].replace({"Yes": 1, "No": 2}, inplace=True)
df["Teh"].replace({"Yes": 1, "No": 2}, inplace=True)

"""# Multiple Regression"""

# Define independent variables (X) and dependent variable (y)
import statsmodels.api as sm

X = df[["Age","Gender","Slpdrn","Exerq","Ssl","Wsl","Alcsm","Smkhbt","Fist","Diqlt","Fhomi","Rlst","Suh","Ses","Smu","Alvl","Dplvl","Wlb","Teh"]]
y = df["Mhs"]  # Mental Health Score

# Add a constant for the intercept
X = sm.add_constant(X)

# Fit the multiple linear regression model
model = sm.OLS(y, X).fit()

# Display the model summary
print(model.summary())

"""Here we have  multiple regression model with all the independent variables.

Here Our null hypothesis is all the variable we have chosen are correct and all have the effect on the mhs

Our alternate hypothesis will be some of the independent variable are useless so we can remove them.
"""

# Define independent variables (X) and dependent variable (y)
import statsmodels.api as sm

X = df[["Exerq","Ssl","Wsl","Fist","Fhomi","Smu","Alvl","Dplvl","Wlb",]]
y = df["Mhs"]  # Mental Health Score

# Add a constant for the intercept
X = sm.add_constant(X)

# Fit the multiple linear regression model
model = sm.OLS(y, X).fit()

# Display the model summary
print(model.summary())

# Define independent variables (X) and dependent variable (y)
import statsmodels.api as sm

X = df[["Age","Gender","Slpdrn","Alcsm","Smkhbt","Diqlt","Rlst","Suh","Ses","Teh"]]
y = df["Mhs"]  # Mental Health Score

# Add a constant for the intercept
X = sm.add_constant(X)

# Fit the multiple linear regression model
model = sm.OLS(y, X).fit()

# Display the model summary
print(model.summary())

#This are the removed variables, as they have p-value > 0.05.

"""# First order model"""

# Define independent variables (X) and dependent variable (y)
import statsmodels.api as sm

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb",]] # removed Fhomi as it is categorial variable
y = df["Mhs"]  # Mental Health Score

# Add a constant for the intercept
X = sm.add_constant(X)

# Fit the multiple linear regression model
model = sm.OLS(y, X).fit()

# Display the model summary
print(model.summary())

#First order model
X = df[["Exerq","Ssl","Wsl","Fist","Smu","Fhomi","Alvl","Dplvl","Wlb"]]
y = df["Mhs"]
X_full = sm.add_constant(X)
model = sm.OLS(y, X_full).fit()
print("Baseline First-Order Model Summary:")
print(model.summary())

"""# Interaction Model"""

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb","Fhomi"]] # removed Fhomi as it is categorial variable
y = df["Mhs"]  # Mental Health Score
X_interaction = X.copy()
X_interaction["Alvl_Dplvl"] = X_interaction["Alvl"] * X_interaction["Dplvl"]
df["Alvl_Dplvl"]=X_interaction["Alvl_Dplvl"]

X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Fhomi","Alvl_Dplvl"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb","Fhomi"]] # removed Fhomi as it is categorial variable
y = df["Mhs"]  # Mental Health Score
X_interaction = X.copy()
X_interaction["Exerq_Dplvl"] = X_interaction["Exerq"] * X_interaction["Dplvl"]
df["Exerq_Dplvl"]=X_interaction["Exerq_Dplvl"]

X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Fhomi","Exerq_Dplvl"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb","Fhomi"]] # removed Fhomi as it is categorial variable
y = df["Mhs"]  # Mental Health Score
X_interaction = X.copy()
X_interaction["Wsl_Alvl"] = X_interaction["Wsl"] * X_interaction["Alvl"]
df["Wsl_Alvl"]=X_interaction["Wsl_Alvl"]

X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Fhomi","Wsl_Alvl"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb","Fhomi"]] # removed Fhomi as it is categorial variable
y = df["Mhs"]  # Mental Health Score
X_interaction = X.copy()
X_interaction["Fist_Wsl"] = X_interaction["Fist"] * X_interaction["Wsl"]
df["Fist_Wsl"]=X_interaction["Fist_Wsl"]

X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Fhomi","Fist_Wsl"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb","Fhomi"]] # removed Fhomi as it is categorial variable
y = df["Mhs"]  # Mental Health Score
X_interaction = X.copy()
X_interaction["Smu_Ssl"] = X_interaction["Smu"] * X_interaction["Ssl"]
df["Smu_Ssl"]=X_interaction["Smu_Ssl"]

X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Fhomi","Smu_Ssl"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb","Fhomi"]] # removed Fhomi as it is categorial variable
y = df["Mhs"]  # Mental Health Score
X_interaction = X.copy()
X_interaction["Alvl_Dplvl"] = X_interaction["Alvl"] * X_interaction["Dplvl"]
df["Alvl_Dplvl"]=X_interaction["Alvl_Dplvl"]

X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Fhomi","Alvl_Dplvl"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb","Fhomi"]] # removed Fhomi as it is categorial variable
y = df["Mhs"]  # Mental Health Score
X_interaction = X.copy()
X_interaction["Fist_Dplvl"] = X_interaction["Fist"] * X_interaction["Dplvl"]
df["Fist_Dplvl"]=X_interaction["Fist_Dplvl"]

X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Fhomi","Fist_Dplvl"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb","Fhomi"]] # removed Fhomi as it is categorial variable
y = df["Mhs"]  # Mental Health Score
X_interaction = X.copy()
X_interaction["Wsl_Dplvl"] = X_interaction["Wsl"] * X_interaction["Dplvl"]
df["Wsl_Dplvl"]=X_interaction["Wsl_Dplvl"]

X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Fhomi","Wsl_Dplvl"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

"""# Checking for VIF in highest R-squared value model (Interaction model)"""

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb","Fhomi"]] # removed Fhomi as it is categorial variable
y = df["Mhs"]  # Mental Health Score
import statsmodels.api as sm

#"Alvl_Dplvl","Wlb_sq"

# Run the regression model
X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Alvl_Dplvl"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

# Extracting p-values for hypothesis testing
p_values = model.pvalues
print("\nP-values of independent variables:\n", p_values)

# Checking significance at α = 0.05
significant_vars = p_values[p_values < 0.05]
print("\nSignificant variables (p < 0.05):\n", significant_vars)

# --- VIF Calculation ---
vif_data = pd.DataFrame()
vif_data["Variable"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print("Variance Inflation Factor (VIF) for each variable:")
print(vif_data)

# --- Train-Test Split ---
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Add constant to both train and test sets
X_train_full = sm.add_constant(X_train)
X_test_full = sm.add_constant(X_test)

# Fit the model on the training data
model_train = sm.OLS(y_train, X_train_full).fit()

# Display the training model summary
#print("\nTraining Model Summary:")
#print(model_train.summary())

# Predictions on training and test sets
y_train_pred = model_train.predict(X_train_full)
y_test_pred = model_train.predict(X_test_full)

# Calculate performance metrics
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

# Display performance metrics
print("\nPerformance Metrics:")
print(f"Training MSE: {train_mse:.4f}")
print(f"Test MSE: {test_mse:.4f}")
print(f"Training R-squared: {train_r2:.4f}")
print(f"Test R-squared: {test_r2:.4f}")

# Check p-values for significance on the training model
#p_values_train = model_train.pvalues
#print("\nP-values of independent variables (Training Model):\n", p_values_train)

#significant_vars_train = p_values_train[p_values_train < 0.05]
#print("\nSignificant variables (p < 0.05) in Training Model:\n", significant_vars_train)

"""# Second order model"""

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Alvl","Dplvl","Wlb","Fhomi"]]
y= df["Mhs"]

X_quadratic = X.copy()
X_quadratic["Exerq_sq"] = X_quadratic["Exerq"] ** 2
df["Exerq_sq"]=X_quadratic["Exerq_sq"]
X_quadratic = sm.add_constant(X_quadratic)
model_quadratic = sm.OLS(y, X_quadratic).fit()
print("\nQuadratic Model Summary (Exerq^2):")
print(model_quadratic.summary())

X_quadratic = X.copy()
X_quadratic["Ssl_sq"] = X_quadratic["Ssl"] ** 2
df["Ssl_sq"]=X_quadratic["Ssl_sq"]
X_quadratic = sm.add_constant(X_quadratic)
model_quadratic = sm.OLS(y, X_quadratic).fit()
print("\nQuadratic Model Summary (Ssl^2):")
print(model_quadratic.summary())

X_quadratic = X.copy()
X_quadratic["Wsl_sq"] = X_quadratic["Wsl"] ** 2
df["Wsl_sq"]=X_quadratic["Wsl_sq"]
X_quadratic = sm.add_constant(X_quadratic)
model_quadratic = sm.OLS(y, X_quadratic).fit()
print("\nQuadratic Model Summary (Wsl^2):")
print(model_quadratic.summary())

X_quadratic = X.copy()
X_quadratic["Fist_sq"] = X_quadratic["Fist"] ** 2
df["Fist_sq"]=X_quadratic["Fist_sq"]
X_quadratic = sm.add_constant(X_quadratic)
model_quadratic = sm.OLS(y, X_quadratic).fit()
print("\nQuadratic Model Summary (Fist^2):")
print(model_quadratic.summary())

X_quadratic = X.copy()
X_quadratic["Smu_sq"] = X_quadratic["Smu"] ** 2
df["Smu_sq"]=X_quadratic["Smu_sq"]
X_quadratic = sm.add_constant(X_quadratic)
model_quadratic = sm.OLS(y, X_quadratic).fit()
print("\nQuadratic Model Summary (Smu^2):")
print(model_quadratic.summary())

X_quadratic = X.copy()
X_quadratic["Alvl_sq"] = X_quadratic["Alvl"] ** 2
df["Alvl_sq"]=X_quadratic["Alvl_sq"]
X_quadratic = sm.add_constant(X_quadratic)
model_quadratic = sm.OLS(y, X_quadratic).fit()
print("\nQuadratic Model Summary (Alvl^2):")
print(model_quadratic.summary())

X_quadratic = X.copy()
X_quadratic["Dplvl_sq"] = X_quadratic["Dplvl"] ** 2
df["Dplvl_sq"]=X_quadratic["Dplvl_sq"]
X_quadratic = sm.add_constant(X_quadratic)
model_quadratic = sm.OLS(y, X_quadratic).fit()
print("\nQuadratic Model Summary (Dplvl^2):")
print(model_quadratic.summary())

X_quadratic = X.copy()
X_quadratic["Wlb_sq"] = X_quadratic["Wlb"] ** 2
df["Wlb_sq"]=X_quadratic["Wlb_sq"]
X_quadratic = sm.add_constant(X_quadratic)
model_quadratic = sm.OLS(y, X_quadratic).fit()
print("\nQuadratic Model Summary (Wlb^2):")
print(model_quadratic.summary())

X_quadratic = X.copy()
X_quadratic["Fhomi_sq"] = X_quadratic["Fhomi"] ** 2
df["Fhomi_sq"]=X_quadratic["Fhomi_sq"]
X_quadratic = sm.add_constant(X_quadratic)
model_quadratic = sm.OLS(y, X_quadratic).fit()
print("\nQuadratic Model Summary (Fhomi^2):")
print(model_quadratic.summary())

"""# Checking VIF for highest R-squared value (Second order model)"""

import statsmodels.api as sm

#"Alvl_Dplvl","Wlb_sq"

# Run the regression model
X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Wlb_sq"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

# Extracting p-values for hypothesis testing
p_values = model.pvalues
print("\nP-values of independent variables:\n", p_values)

# Checking significance at α = 0.05
significant_vars = p_values[p_values < 0.05]
print("\nSignificant variables (p < 0.05):\n", significant_vars)

from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# --- VIF Calculation ---
vif_data = pd.DataFrame()
vif_data["Variable"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print("Variance Inflation Factor (VIF) for each variable:")
print(vif_data)

# --- Train-Test Split ---
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Add constant to both train and test sets
X_train_full = sm.add_constant(X_train)
X_test_full = sm.add_constant(X_test)

# Fit the model on the training data
model_train = sm.OLS(y_train, X_train_full).fit()

# Display the training model summary
#print("\nTraining Model Summary:")
#print(model_train.summary())

# Predictions on training and test sets
y_train_pred = model_train.predict(X_train_full)
y_test_pred = model_train.predict(X_test_full)

# Calculate performance metrics
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

# Display performance metrics
print("\nPerformance Metrics:")
print(f"Training MSE: {train_mse:.4f}")
print(f"Test MSE: {test_mse:.4f}")
print(f"Training R-squared: {train_r2:.4f}")
print(f"Test R-squared: {test_r2:.4f}")

# Check p-values for significance on the training model
#p_values_train = model_train.pvalues
#print("\nP-values of independent variables (Training Model):\n", p_values_train)

#significant_vars_train = p_values_train[p_values_train < 0.05]
#print("\nSignificant variables (p < 0.05) in Training Model:\n", significant_vars_train)

"""# Log transformation"""

X = df[["Exerq","Ssl","Wsl","Fist","Smu","Fhomi","Alvl","Dplvl","Wlb"]]
y= df["Mhs"]

X_transform = X.copy()
df["Exerq_log"] = np.log(df["Exerq"] + abs(df["Exerq"].min()) + 1)  # Shift to avoid log(0) or log(negative)
X_transform["Exerq_log"] = df["Exerq_log"]
X_transform = sm.add_constant(X_transform)
model_transform = sm.OLS(y, X_transform).fit()
print("\nTransformation Model Summary (Log Exerq):")
print(model_transform.summary())

X_transform = X.copy()
df["Ssl_log"] = np.log(df["Ssl"] + abs(df["Ssl"].min()) + 1)  # Shift to avoid log(0) or log(negative)
X_transform["Ssl_log"] = df["Ssl_log"]
X_transform = sm.add_constant(X_transform)
model_transform = sm.OLS(y, X_transform).fit()
print("\nTransformation Model Summary (Log Ssl):")
print(model_transform.summary())

X_transform = X.copy()
df["Wsl_log"] = np.log(df["Wsl"] + abs(df["Wsl"].min()) + 1)  # Shift to avoid log(0) or log(negative)
X_transform["Wsl_log"] = df["Wsl_log"]
X_transform = sm.add_constant(X_transform)
model_transform = sm.OLS(y, X_transform).fit()
print("\nTransformation Model Summary (Log Wsl):")
print(model_transform.summary())

X_transform = X.copy()
df["Fist_log"] = np.log(df["Fist"] + abs(df["Fist"].min()) + 1)  # Shift to avoid log(0) or log(negative)
X_transform["Fist_log"] = df["Fist_log"]
X_transform = sm.add_constant(X_transform)
model_transform = sm.OLS(y, X_transform).fit()
print("\nTransformation Model Summary (Log Fist):")
print(model_transform.summary())

X_transform = X.copy()
df["Smu_log"] = np.log(df["Smu"] + abs(df["Smu"].min()) + 1)  # Shift to avoid log(0) or log(negative)
X_transform["Smu_log"] = df["Smu_log"]
X_transform = sm.add_constant(X_transform)
model_transform = sm.OLS(y, X_transform).fit()
print("\nTransformation Model Summary (Log Smu):")
print(model_transform.summary())

X_transform = X.copy()
df["Alvl_log"] = np.log(df["Alvl"] + abs(df["Alvl"].min()) + 1)  # Shift to avoid log(0) or log(negative)
X_transform["Alvl_log"] = df["Alvl_log"]
X_transform = sm.add_constant(X_transform)
model_transform = sm.OLS(y, X_transform).fit()
print("\nTransformation Model Summary (Log Alvl):")
print(model_transform.summary())

X_transform = X.copy()
df["Dplvl_log"] = np.log(df["Dplvl"] + abs(df["Dplvl"].min()) + 1)  # Shift to avoid log(0) or log(negative)
X_transform["Dplvl_log"] = df["Dplvl_log"]
X_transform = sm.add_constant(X_transform)
model_transform = sm.OLS(y, X_transform).fit()
print("\nTransformation Model Summary (Log Dplvl):")
print(model_transform.summary())

X_transform = X.copy()
df["Wlb_log"] = np.log(df["Wlb"] + abs(df["Wlb"].min()) + 1)  # Shift to avoid log(0) or log(negative)
X_transform["Wlb_log"] = df["Wlb_log"]
X_transform = sm.add_constant(X_transform)
model_transform = sm.OLS(y, X_transform).fit()
print("\nTransformation Model Summary (Log Wlb):")
print(model_transform.summary())

X_transform = X.copy()
df["Fhomi_log"] = np.log(df["Fhomi"] + abs(df["Fhomi"].min()) + 1)  # Shift to avoid log(0) or log(negative)
X_transform["Fhomi_log"] = df["Fhomi_log"]
X_transform = sm.add_constant(X_transform)
model_transform = sm.OLS(y, X_transform).fit()
print("\nTransformation Model Summary (Log Fhomi):")
print(model_transform.summary())

"""#Checking VIF for highest R-squared value (Second order model)"""

import statsmodels.api as sm

#"Alvl_Dplvl","Wlb_sq"

# Run the regression model
X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb","Exerq_log"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

# Extracting p-values for hypothesis testing
p_values = model.pvalues
print("\nP-values of independent variables:\n", p_values)

# Checking significance at α = 0.05
significant_vars = p_values[p_values < 0.05]
print("\nSignificant variables (p < 0.05):\n", significant_vars)

from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# --- VIF Calculation ---
vif_data = pd.DataFrame()
vif_data["Variable"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print("Variance Inflation Factor (VIF) for each variable:")
print(vif_data)

# --- Train-Test Split ---
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Add constant to both train and test sets
X_train_full = sm.add_constant(X_train)
X_test_full = sm.add_constant(X_test)

# Fit the model on the training data
model_train = sm.OLS(y_train, X_train_full).fit()

# Display the training model summary
#print("\nTraining Model Summary:")
#print(model_train.summary())

# Predictions on training and test sets
y_train_pred = model_train.predict(X_train_full)
y_test_pred = model_train.predict(X_test_full)

# Calculate performance metrics
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

# Display performance metrics
print("\nPerformance Metrics:")
print(f"Training MSE: {train_mse:.4f}")
print(f"Test MSE: {test_mse:.4f}")
print(f"Training R-squared: {train_r2:.4f}")
print(f"Test R-squared: {test_r2:.4f}")

# Check p-values for significance on the training model
#p_values_train = model_train.pvalues
#print("\nP-values of independent variables (Training Model):\n", p_values_train)

#significant_vars_train = p_values_train[p_values_train < 0.05]
#print("\nSignificant variables (p < 0.05) in Training Model:\n", significant_vars_train)

"""# First order model selection after comparing model"""

import statsmodels.api as sm

# Run the regression model
X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Fhomi", "Alvl", "Dplvl", "Wlb"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

# Extracting p-values for hypothesis testing
p_values = model.pvalues
print("\nP-values of independent variables:\n", p_values)

# Checking significance at α = 0.05
significant_vars = p_values[p_values < 0.05]
print("\nSignificant variables (p < 0.05):\n", significant_vars)

plt.scatter(df["Mhs"],df["Exerq"])
plt.xlabel("Mhs")
plt.ylabel("Exerq")
plt.show()

plt.scatter(df["Mhs"],df["Ssl"])
plt.xlabel("Mhs")
plt.ylabel("Ssl")
plt.show()

plt.scatter(df["Mhs"],df["Wsl"])
plt.xlabel("Mhs")
plt.ylabel("Wsl")
plt.show()

plt.scatter(df["Mhs"],df["Fist"])
plt.xlabel("Mhs")
plt.ylabel("Fist")
plt.show()

plt.scatter(df["Mhs"],df["Fhomi"])
plt.xlabel("Mhs")
plt.ylabel("Fhomi")
plt.show()

plt.scatter(df["Mhs"],df["Smu"])
plt.xlabel("Mhs")
plt.ylabel("Smu")
plt.show()

plt.scatter(df["Mhs"],df["Alvl"])
plt.xlabel("Mhs")
plt.ylabel("Alvl")
plt.show()

plt.scatter(df["Mhs"],df["Dplvl"])
plt.xlabel("Mhs")
plt.ylabel("Dplvl")
plt.show()

plt.scatter(df["Mhs"],df["Wlb"])
plt.xlabel("Mhs")
plt.ylabel("Wlb")
plt.show()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Forward Selection Function
def forward_selection(X_train, y_train, significance_level=0.05):
    initial_features = []
    remaining_features = list(X_train.columns)

    while remaining_features:
        pvals = {}
        for feature in remaining_features:
            current_features = initial_features + [feature]
            X_current = sm.add_constant(X_train[current_features])
            model = sm.OLS(y_train, X_current).fit()
            pvals[feature] = model.pvalues[feature]

        # Find feature with minimum p-value
        min_pval_feature = min(pvals, key=pvals.get)
        min_pval = pvals[min_pval_feature]

        if min_pval < significance_level:
            initial_features.append(min_pval_feature)
            remaining_features.remove(min_pval_feature)
        else:
            break

    return initial_features

# Run forward selection
selected_features = forward_selection(X_train, y_train)
print("Forward Selection - Selected Features:", selected_features)

# Fit model with selected features
X_train_selected = sm.add_constant(X_train[selected_features])
model_forward = sm.OLS(y_train, X_train_selected).fit()

# Test on test set
X_test_selected = sm.add_constant(X_test[selected_features])
y_pred = model_forward.predict(X_test_selected)

# Evaluate model
from sklearn.metrics import r2_score, mean_squared_error
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

# Print results
print("\nForward Selection Model Summary (Training Data):")
print(model_forward.summary())
print("\nTest Set Performance:")
print(f"R-squared: {r2:.4f}")
print(f"MSE: {mse:.4f}")

# Baseline model with all features for comparison
X_train_full = sm.add_constant(X_train)
baseline_model = sm.OLS(y_train, X_train_full).fit()
print("\nBaseline Model Summary (All Features):")
print(baseline_model.summary())

def backward_elimination(X_train, y_train, significance_level=0.05):
    features = list(X_train.columns)

    while len(features) > 0:
        X_current = sm.add_constant(X_train[features])
        model = sm.OLS(y_train, X_current).fit()
        p_values = model.pvalues[1:]  # Exclude constant

        max_pval = p_values.max()
        if max_pval > significance_level:
            feature_to_remove = p_values.idxmax()
            features.remove(feature_to_remove)
        else:
            break

    return features

# Run backward elimination
selected_features = backward_elimination(X_train, y_train)
print("Backward Elimination - Selected Features:", selected_features)

# Fit model with selected features
X_train_selected = sm.add_constant(X_train[selected_features])
model_backward = sm.OLS(y_train, X_train_selected).fit()

# Test on test set
X_test_selected = sm.add_constant(X_test[selected_features])
y_pred = model_backward.predict(X_test_selected)

# Evaluate model
from sklearn.metrics import r2_score, mean_squared_error
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

# Print results
print("\nBackward Elimination Model Summary (Training Data):")
print(model_backward.summary())
print("\nTest Set Performance:")
print(f"R-squared: {r2:.4f}")
print(f"MSE: {mse:.4f}")

# Baseline model with all features for comparison
X_train_full = sm.add_constant(X_train)
baseline_model = sm.OLS(y_train, X_train_full).fit()
print("\nBaseline Model Summary (All Features):")
print(baseline_model.summary())

from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# --- VIF Calculation ---
vif_data = pd.DataFrame()
vif_data["Variable"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print("Variance Inflation Factor (VIF) for each variable:")
print(vif_data)

# --- Train-Test Split ---
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Add constant to both train and test sets
X_train_full = sm.add_constant(X_train)
X_test_full = sm.add_constant(X_test)

# Fit the model on the training data
model_train = sm.OLS(y_train, X_train_full).fit()

# Display the training model summary
#print("\nTraining Model Summary:")
#print(model_train.summary())

# Predictions on training and test sets
y_train_pred = model_train.predict(X_train_full)
y_test_pred = model_train.predict(X_test_full)

# Calculate performance metrics
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

# Display performance metrics
print("\nPerformance Metrics:")
print(f"Training MSE: {train_mse:.4f}")
print(f"Test MSE: {test_mse:.4f}")
print(f"Training R-squared: {train_r2:.4f}")
print(f"Test R-squared: {test_r2:.4f}")

# Check p-values for significance on the training model
#p_values_train = model_train.pvalues
#print("\nP-values of independent variables (Training Model):\n", p_values_train)

#significant_vars_train = p_values_train[p_values_train < 0.05]
#print("\nSignificant variables (p < 0.05) in Training Model:\n", significant_vars_train)

residuals = y_train - y_train_pred
plt.figure(figsize=(8, 6))
plt.hist(residuals, bins=20, edgecolor='black', color='skyblue')
plt.title('Histogram of Residuals (Training Data)', fontsize=14)
plt.xlabel('Residuals', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

plt.figure(figsize=(9, 6))
# Add the residuals as a column to the DataFrame
df["residual"] = residuals
stats.probplot(df["residual"], dist="norm", plot=plt)
plt.title('Q-Q Plot for Mental Health Score', fontsize=20, fontweight='semibold', color='#222222', pad=15)
plt.xlabel('Theoretical Quantiles', fontsize=16, color='#333333', labelpad=10)
plt.ylabel('Ordered Values', fontsize=16, color='#333333', labelpad=10)
plt.grid(True, linestyle='--', alpha=0.7, color='#E0E0E0')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
plt.scatter(y_train_pred, residuals, color='blue', alpha=0.5, edgecolor='black')
plt.axhline(y=0, color='red', linestyle='--', linewidth=1)  # Horizontal line at 0
plt.title('Residuals vs Predicted Values (Training Data)', fontsize=14)
plt.xlabel('Predicted Values (y_bar)', fontsize=12)
plt.ylabel('Residuals', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

residuals_std = np.std(residuals)
outlier_threshold = 2 * residuals_std
outliers = np.abs(residuals) > outlier_threshold
plt.figure(figsize=(8, 6))
plt.scatter(y_train_pred[~outliers], residuals[~outliers], color='blue', alpha=0.5, label='Non-Outliers')
plt.scatter(y_train_pred[outliers], residuals[outliers], color='red', alpha=0.7, label='Outliers')
plt.axhline(y=0, color='black', linestyle='--', linewidth=1)
plt.axhline(y=outlier_threshold, color='green', linestyle='--', linewidth=1, label=f'±2 SD ({outlier_threshold:.2f})')
plt.axhline(y=-outlier_threshold, color='green', linestyle='--', linewidth=1)
plt.title('Residuals vs. Predicted Values with Outliers (Training Data)', fontsize=14)
plt.xlabel('Predicted Values (y_bar)', fontsize=12)
plt.ylabel('Residuals', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

y_test_pred = model_train.predict(X_test_full)
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

print("\nPerformance Metrics:")
print(f"Training MSE: {train_mse:.4f}")
print(f"Test MSE: {test_mse:.4f}")
print(f"Training R-squared: {train_r2:.4f}")
print(f"Test R-squared: {test_r2:.4f}")

from scipy.stats import shapiro, probplot
plt.figure(figsize=(8, 6))
probplot(residuals, dist="norm", plot=plt)
plt.title('Q-Q Plot of Residuals (Training Data)', fontsize=14)
plt.xlabel('Theoretical Quantiles', fontsize=12)
plt.ylabel('Sample Quantiles', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()


shapiro_stat, shapiro_p = shapiro(residuals)
print("\nShapiro-Wilk Test for Normality:")
print(f"Statistic: {shapiro_stat:.4f}")
print(f"P-value: {shapiro_p:.4f}")

"""# Final Model after removing Fhomi"""

import statsmodels.api as sm
#removing fhomi
# Run the regression model
X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Alvl", "Dplvl", "Wlb"]]
y = df["Mhs"]
X_full = sm.add_constant(X)  # Add intercept
model = sm.OLS(y, X_full).fit()

# Display the model summary
print("Baseline First-Order Model Summary:")
print(model.summary())

# Extracting p-values for hypothesis testing
p_values = model.pvalues
print("\nP-values of independent variables:\n", p_values)

# Checking significance at α = 0.05
significant_vars = p_values[p_values < 0.05]
print("\nSignificant variables (p < 0.05):\n", significant_vars)

from sklearn.model_selection import train_test_split
#X = df[["Exerq", "Ssl", "Wsl", "Fist", "Smu", "Fhomi", "Alvl", "Dplvl", "Wlb"]]
#y = df["Mhs"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Forward Selection Function
def forward_selection(X_train, y_train, significance_level=0.05):
    initial_features = []
    remaining_features = list(X_train.columns)

    while remaining_features:
        pvals = {}
        for feature in remaining_features:
            current_features = initial_features + [feature]
            X_current = sm.add_constant(X_train[current_features])
            model = sm.OLS(y_train, X_current).fit()
            pvals[feature] = model.pvalues[feature]

        # Find feature with minimum p-value
        min_pval_feature = min(pvals, key=pvals.get)
        min_pval = pvals[min_pval_feature]

        if min_pval < significance_level:
            initial_features.append(min_pval_feature)
            remaining_features.remove(min_pval_feature)
        else:
            break

    return initial_features

# Run forward selection
selected_features = forward_selection(X_train, y_train)
print("Forward Selection - Selected Features:", selected_features)

# Fit model with selected features
X_train_selected = sm.add_constant(X_train[selected_features])
model_forward = sm.OLS(y_train, X_train_selected).fit()

# Test on test set
X_test_selected = sm.add_constant(X_test[selected_features])
y_pred = model_forward.predict(X_test_selected)

# Evaluate model
from sklearn.metrics import r2_score, mean_squared_error
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

# Print results
print("\nForward Selection Model Summary (Training Data):")
print(model_forward.summary())
print("\nTest Set Performance:")
print(f"R-squared: {r2:.4f}")
print(f"MSE: {mse:.4f}")

# Baseline model with all features for comparison
X_train_full = sm.add_constant(X_train)
baseline_model = sm.OLS(y_train, X_train_full).fit()
print("\nBaseline Model Summary (All Features):")
print(baseline_model.summary())

def backward_elimination(X_train, y_train, significance_level=0.05):
    features = list(X_train.columns)

    while len(features) > 0:
        X_current = sm.add_constant(X_train[features])
        model = sm.OLS(y_train, X_current).fit()
        p_values = model.pvalues[1:]  # Exclude constant

        max_pval = p_values.max()
        if max_pval > significance_level:
            feature_to_remove = p_values.idxmax()
            features.remove(feature_to_remove)
        else:
            break

    return features

# Run backward elimination
selected_features = backward_elimination(X_train, y_train)
print("Backward Elimination - Selected Features:", selected_features)

# Fit model with selected features
X_train_selected = sm.add_constant(X_train[selected_features])
model_backward = sm.OLS(y_train, X_train_selected).fit()

# Test on test set
X_test_selected = sm.add_constant(X_test[selected_features])
y_pred = model_backward.predict(X_test_selected)

# Evaluate model
from sklearn.metrics import r2_score, mean_squared_error
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

# Print results
print("\nBackward Elimination Model Summary (Training Data):")
print(model_backward.summary())
print("\nTest Set Performance:")
print(f"R-squared: {r2:.4f}")
print(f"MSE: {mse:.4f}")

# Baseline model with all features for comparison
X_train_full = sm.add_constant(X_train)
baseline_model = sm.OLS(y_train, X_train_full).fit()
print("\nBaseline Model Summary (All Features):")
print(baseline_model.summary())

from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# --- VIF Calculation ---
vif_data = pd.DataFrame()
vif_data["Variable"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
print("Variance Inflation Factor (VIF) for each variable:")
print(vif_data)

# --- Train-Test Split ---
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Add constant to both train and test sets
X_train_full = sm.add_constant(X_train)
X_test_full = sm.add_constant(X_test)

# Fit the model on the training data
model_train = sm.OLS(y_train, X_train_full).fit()

# Display the training model summary
#print("\nTraining Model Summary:")
#print(model_train.summary())

# Predictions on training and test sets
y_train_pred = model_train.predict(X_train_full)
y_test_pred = model_train.predict(X_test_full)

# Calculate performance metrics
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

# Display performance metrics
print("\nPerformance Metrics:")
print(f"Training MSE: {train_mse:.4f}")
print(f"Test MSE: {test_mse:.4f}")
print(f"Training R-squared: {train_r2:.4f}")
print(f"Test R-squared: {test_r2:.4f}")

# Check p-values for significance on the training model
#p_values_train = model_train.pvalues
#print("\nP-values of independent variables (Training Model):\n", p_values_train)

#significant_vars_train = p_values_train[p_values_train < 0.05]
#print("\nSignificant variables (p < 0.05) in Training Model:\n", significant_vars_train)

residuals = y_train - y_train_pred
plt.figure(figsize=(8, 6))
plt.hist(residuals, bins=20, edgecolor='black', color='skyblue')
plt.title('Histogram of Residuals (Training Data)', fontsize=14)
plt.xlabel('Residuals', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

plt.figure(figsize=(9, 6))
# Add the residuals as a column to the DataFrame
df["residual"] = residuals
stats.probplot(df["residual"], dist="norm", plot=plt)
plt.title('Q-Q Plot for Mental Health Score', fontsize=20, fontweight='semibold', color='#222222', pad=15)
plt.xlabel('Theoretical Quantiles', fontsize=16, color='#333333', labelpad=10)
plt.ylabel('Ordered Values', fontsize=16, color='#333333', labelpad=10)
plt.grid(True, linestyle='--', alpha=0.7, color='#E0E0E0')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
plt.scatter(y_train_pred, residuals, color='blue', alpha=0.5, edgecolor='black')
plt.axhline(y=0, color='red', linestyle='--', linewidth=1)  # Horizontal line at 0
plt.title('Residuals vs Predicted Values (Training Data)', fontsize=14)
plt.xlabel('Predicted Values (y_bar)', fontsize=12)
plt.ylabel('Residuals', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

residuals_std = np.std(residuals)
outlier_threshold = 2 * residuals_std
outliers = np.abs(residuals) > outlier_threshold
plt.figure(figsize=(8, 6))
plt.scatter(y_train_pred[~outliers], residuals[~outliers], color='blue', alpha=0.5, label='Non-Outliers')
plt.scatter(y_train_pred[outliers], residuals[outliers], color='red', alpha=0.7, label='Outliers')
plt.axhline(y=0, color='black', linestyle='--', linewidth=1)
plt.axhline(y=outlier_threshold, color='green', linestyle='--', linewidth=1, label=f'±2 SD ({outlier_threshold:.2f})')
plt.axhline(y=-outlier_threshold, color='green', linestyle='--', linewidth=1)
plt.title('Residuals vs. Predicted Values with Outliers (Training Data)', fontsize=14)
plt.xlabel('Predicted Values (y_bar)', fontsize=12)
plt.ylabel('Residuals', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

y_test_pred = model_train.predict(X_test_full)
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

print("\nPerformance Metrics:")
print(f"Training MSE: {train_mse:.4f}")
print(f"Test MSE: {test_mse:.4f}")
print(f"Training R-squared: {train_r2:.4f}")
print(f"Test R-squared: {test_r2:.4f}")

from scipy.stats import shapiro, probplot
plt.figure(figsize=(8, 6))
probplot(residuals, dist="norm", plot=plt)
plt.title('Q-Q Plot of Residuals (Training Data)', fontsize=14)
plt.xlabel('Theoretical Quantiles', fontsize=12)
plt.ylabel('Sample Quantiles', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()


shapiro_stat, shapiro_p = shapiro(residuals)
print("\nShapiro-Wilk Test for Normality:")
print(f"Statistic: {shapiro_stat:.4f}")
print(f"P-value: {shapiro_p:.4f}")

# ANOVA test for categorical variables
print("ANOVA test results for categorical variables:")
for col in categorical_cols:
    groups = [df[df[col] == val]['Mhs'].values for val in df[col].unique()]
    f_val, p_val = stats.f_oneway(*groups)
    print(f"{col}: F-value = {f_val:.4f}, p-value = {p_val:.4f}")